services:
  postgres:
    container_name: postgres
    image: postgres:15
    platform: linux/x86_64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "book-manager"
