spring.application.name: book-manager-api


server:
  port: 9099
  servlet:
    context-path: /book-manager-api

spring.profiles.group:
  local:
    - datasource-local
  test:
    - datasource-test

spring-doc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring.config.activate.on-profile: local

logging.level:
  web: DEBUG
  org.springframework: DEBUG
  com.quo.book.manager: DEBUG
  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter: DEBUG
  org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

---

spring.config.activate.on-profile: test
logging.level:
  web: DEBUG
  org.springframework: DEBUG
  com.quo.book.manager: DEBUG
  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter: DEBUG
  org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
